### ISSUE TITLE
"Wait for a bot" issue

### ISSUE THREAD

**Issue by claudetheboof** [Leeon123/Python3-Botnet#1]
so I tried to run the `cnc.py 80` then I keep on getting Wait for a bot , do I need to setup a virtual bot website for this to work?

**Comment by Leeon123** [comment]
?

**Comment by Leeon123** [comment]
it need to have a bot at first.

**Comment by claudetheboof** [comment]
And how do I set up these "bots"? Does it came with the project? Or do I have to find my own ?

**Comment by Leeon123** [comment]
Using bot.py, U need to edit the bot.py's ip and port options and run it

**Comment by claudetheboof** [comment]
You mind giving me full instruction on how to use it? For example which scripts to run first and  maybe it's parameters

**Comment by Leeon123** [comment]
first edit ur server ip to bot.py and run it on other server or pc , then run cnc.py on ur first server , the bot will connect to ur server after U run it and set it correctly.
